<?php
/**
 *
 * @category   Diconium
 * @package    Diconium_DigitalRiver
 */
 
// Logic for click on test credential button api call.
?>
<?php if($block->getApiKey()) { ?> 
<input type="hidden" value="api_key" name="hiden_api_key"/>
<?php } ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        var collectSpan = jQuery('#collect_span');
        jQuery('#test_api_button').on('click', function () {
            if(jQuery('input[name="hiden_api_key"]').length) { 
                jQuery.ajax({ 
                    type : "GET",
                    url : "<?php echo $block->getAjaxUrl() ?>",
                    contentType: "application/json; charset=UTF-8",
                    beforeSend: function() {
                        collectSpan.find('.collected').hide();
                        collectSpan.find('.processing').show();
                        jQuery('#collect_message_span').text('');
                    },
                    success: function (response) {  
                        collectSpan.find('.processing').hide();
                        resultText = 'Success';
                        collectSpan.find('.collected').show();
                        jQuery('#collect_message_span').text(resultText);
                    },
                    error: function (e) {
                        collectSpan.find('.processing').hide();
                        resultText = 'Failed';
                        collectSpan.find('.removed').show();
                        jQuery('#collect_message_span').text(resultText);
                    } 
                }) 
            }else{
                collectSpan.find('.processing').hide();
                resultText = 'Api Key not found';
                collectSpan.find('.removed').show();
                jQuery('#collect_message_span').text(resultText);
            } 
        });
    });
</script>   
<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <img class="removed" hidden="hidden" alt="Collected" style="margin:-1px 4px" src="<?php echo $block->getViewFileUrl('images/rule_component_remove.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>
